name: Local
variables:
  - name: baseUrl
    value: http://localhost:8080
  - name: gatewayUrl
    value: http://localhost:8080
  - name: identityUrl
    value: http://localhost:8084
  - name: inventoryUrl
    value: http://localhost:8081
  - name: ordersUrl
    value: http://localhost:8082
  - name: shippingUrl
    value: http://localhost:8083
  - name: token
    value: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzbWFydGxvZ2l4LWlkZW50aXR5LXNlcnZpY2UiLCJzdWIiOiJhZG1pbkBzbWFydGxvZ2l4LmNsIiwicm9sZSI6IkFETUlOIiwiZXhwIjoxNzc4NzIwNzk3LCJpYXQiOjE3Nzg3MTcxOTcsInVzZXJJZCI6MX0.EKdA1FaE2a40NO3208Mj4OkHz_0_0TBhxIellG2tFug
  - name: orderId
    value: ""
  - name: orderNumber
    value: ""
  - name: shipmentId
    value: ""
  - name: shipmentNumber
    value: ""
  - name: productId
    value: "1"
  - name: warehouseId
    value: "1"
  - name: customerId
    value: "1"
